name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, veldersoares ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: 
    #   image: kirschbaumdevelopment/laravel-test-runner:7.4
    env:
      # extensions: gd, ctype, iconv, json, mbstring, dom, fileinfo, xml, xsl, zip, curl, bcmath, intl
      extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # - name: Setup PHP cache environment
      #   id: ext-cache
      #   uses: shivammathur/cache-extensions@v1
      #   with:
      #     php-version: '7.4'
      #     extensions: ${{ env.extensions }}
      #     key: php-v6

      # - name: Cache PHP extensions
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ steps.ext-cache.outputs.dir }}
      #     key: ${{ steps.ext-cache.outputs.key }}
      #     restore-keys: ${{ steps.ext-cache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: prestissimo
          extensions: ${{ env.extensions }}
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Copy CI environment
        run: cp .env.ci .env

      - name: Install Composer
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist  --optimize-autoloader

      - name: Analysys Sintax Code
        run: ./vendor/bin/phpstan analyse src tests --level 7

      - name: Run Insights
        run: ./vendor/bin/phpinsights --no-interaction --min-quality=90 --min-complexity=90 --min-architecture=90 --min-style=90

      - name: Run Tests
        run: vendor/bin/phpunit